### ISSUE TITLE
not close project  

### ISSUE THREAD

**Issue by bjlg** [THUDM/CodeGeeX2#116]
closing project
----------------------------------------------
log:
- JobImpl{Active}@48bc9ef4
	- DeferredCoroutine{Active}@415a334, state: SUSPENDED [ModalityState:{[com.intellij.openapi.progress.impl.JobProviderWithOwnerContext@39c23b80]}, Dispatchers.Default]
		at com.intellij.ide.ShutdownKt$joinBlocking$2$1.invokeSuspend(shutdown.kt:34)
		at com.intellij.openapi.progress.impl.PlatformTaskSupport$runBlockingModalInternal$2$1$mainJob$1.invokeSuspend(PlatformTaskSupport.kt:128)
		- JobImpl{Active}@25d2890d
			- StandaloneCoroutine{Active}@67796f37, state: SUSPENDED [ModalityState:{[com.intellij.openapi.progress.impl.JobProviderWithOwnerContext@39c23b80]}, Dispatchers.Unconfined]
				at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:403)
				at com.intellij.openapi.progress.impl.ChildrenHandler$1.invokeSuspend(ChildrenHandler.kt:32)
		- StandaloneCoroutine{Active}@520e67ae, state: RUNNING [ModalityState:{[com.intellij.openapi.progress.impl.JobProviderWithOwnerContext@39c23b80]}, Dispatchers.Default]
			at java.base@17.0.6/jdk.internal.misc.Unsafe.park(Native Method)
			at java.base@17.0.6/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341)
			at java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506)
			at java.base@17.0.6/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
			at java.base@17.0.6/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
			at java.base@17.0.6/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623)
			at java.desktop/java.awt.EventQueue.getNextEvent(EventQueue.java:579)
			at com.intellij.ide.IdeEventQueue.getNextEvent$lambda$6(IdeEventQueue.kt:461)
			at com.intellij.ide.IdeEventQueue$$Lambda$748/0x000000002f095720.compute(Unknown Source)
			at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:857)
			at com.intellij.ide.IdeEventQueue.getNextEvent(IdeEventQueue.kt:461)
			at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:194)
			at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
			at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
			at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
			at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
			at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
			at java.base@17.0.6/java.security.AccessController.executePrivileged(AccessController.java:776)
			at java.base@17.0.6/java.security.AccessController.doPrivileged(AccessController.java:318)
			at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
			at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
			at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:741)
			at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:466)
			at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1675)
			at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1633)
			at com.intellij.openapi.progress.impl.PlatformTaskSupportKt$showModalIndicator$1$1.invokeSuspend(PlatformTaskSupport.kt:288)
			at com.intellij.openapi.progress.impl.PlatformTaskSupportKt$showModalIndicator$1.invokeSuspend(PlatformTaskSupport.kt:249)
			- StandaloneCoroutine{Active}@5d78c8b9, state: SUSPENDED [ModalityState:{[com.intellij.openapi.progress.impl.JobProviderWithOwnerContext@39c23b80]}, EDT]
				at com.intellij.openapi.progress.impl.PlatformTaskSupportKt.updateFromFlow(PlatformTaskSupport.kt:314)
				at com.intellij.openapi.progress.impl.PlatformTaskSupportKt$showModalIndicator$1$1$2.invokeSuspend(PlatformTaskSupport.kt:263)
				- ProducerCoroutine{Active}@5871055a, state: SUSPENDED [ModalityState:{[com.intellij.openapi.progress.impl.JobProviderWithOwnerContext@39c23b80]}, Dispatchers.Default]
					- ProducerCoroutine{Active}@79632aed, state: SUSPENDED [ModalityState:{[com.intellij.openapi.progress.impl.JobProviderWithOwnerContext@39c23b80]}, Dispatchers.Default]
						at kotlinx.coroutines.flow.StateFlowImpl.collect(StateFlow.kt:403)
			- StandaloneCoroutine{Active}@74ddcc21, state: SUSPENDED [ModalityState:{[com.intellij.openapi.progress.impl.JobProviderWithOwnerContext@39c23b80]}, EDT]
				at com.intellij.util.CoroutinesKt$awaitCancellationAndInvoke$1.invokeSuspend(coroutines.kt:28)

**Comment by crazygo** [comment]
抱歉给你带来了不便，也感谢你提供日志。
现在插件发布了一个新的版本 2.1.1 ，解决了关闭项目会卡顿的问题，欢迎使用。
