### ISSUE TITLE
能否对 code-server 1.65.2 做兼容支持？

### ISSUE THREAD

**Issue by fjqingyou** [THUDM/CodeGeeX2#117]
code-server 这个版本是 nodejs v14 最后一个版本。后面的就升级到了 nodejs v16 了。我这边有一个设备因为一些原因无法无法编译运行比 v14 更高的版本。所以code-server被动锁定在了 1.65.2 上面。请问是否提供这个版本的兼容支持

当前在这个版本上安装 CodeGeeX2 会有如下报错
``` log
[2023-09-24 12:13:59.199] [window] [warning] Settings pattern "security.workspace.*" doesn't match any settings
[2023-09-24 12:14:00.655] [window] [error] ["Incompatible: Can't install 'aminer.codegeex' extension because it is not compatible with the current version of code-server (version 1.65.2).","    at A.checkAndGetCompatibleVersion (/etc/code-server/lib/vscode/out/vs/server/node/server.main.js:102:12154)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)","    at async A.installFromGallery (/etc/code-server/lib/vscode/out/vs/server/node/server.main.js:102:3205)"]
[2023-09-24 12:14:00.680] [window] [error] Can't install 'aminer.codegeex' extension because it is not compatible with the current version of code-server (version 1.65.2).: Incompatible: Can't install 'aminer.codegeex' extension because it is not compatible with the current version of code-server (version 1.65.2).
    at A.checkAndGetCompatibleVersion (/etc/code-server/lib/vscode/out/vs/server/node/server.main.js:102:12154)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async A.installFromGallery (/etc/code-server/lib/vscode/out/vs/server/node/server.main.js:102:3205)
```

**Comment by fjqingyou** [comment]
```
code-server: v4.3.0
版本: 1.65.2
提交: Unknown
日期: 2022-04-14T21:04:05.402Z
浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.36
```
