### ISSUE TITLE
运行run_demo.py成功，但是报错httpx.ConnectTimeout: timed out

### ISSUE THREAD

**Issue by guiniao** [THUDM/CodeGeeX2#191]
运行run_demo.py成功，也能推理写代码，但是，代码返回不全
报错httpx.ConnectTimeout: timed out

**Comment by guiniao** [comment]
报错详细信息：

Traceback (most recent call last):
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/gradio/analytics.py", line 61, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/gradio/analytics.py", line 117, in get_local_ip_address
    ip_address = httpx.get(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_api.py", line 196, in get
    return request(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_api.py", line 104, in request
    return client.request(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
socket.timeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 213, in connect_tcp
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/gradio/analytics.py", line 61, in _do_normal_analytics_request
    data["ip_address"] = get_local_ip_address()
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/gradio/analytics.py", line 117, in get_local_ip_address
    ip_address = httpx.get(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_api.py", line 196, in get
    return request(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_api.py", line 104, in request
    return client.request(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/anaconda/envs/foundation_models/lib/python3.9/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

**Comment by guiniao** [comment]
已解决

**Comment by violet17** [comment]
> 已解决

这是什么原因呢？

**Comment by ZeanNi** [comment]
请问是什么原因？当我部署到AWS也遇到这样相似的错误

**Comment by ZeanNi** [comment]
> 已解决

请问是什么原因？当我部署到AWS也遇到这样相似的错误

**Comment by violet17** [comment]
怎么解决的呢？

**Comment by ZeanNi** [comment]
> 怎么解决的呢？

我是proxy的问题

**Comment by violet17** [comment]
> > 怎么解决的呢？
> 
> 我是proxy的问题

是关掉proxy?  我已经关掉了proxy 但是还是有这个问题。很奇怪。 还有h11 timed out。 好无语啊

**Comment by ZeanNi** [comment]
> > > 怎么解决的呢？
> > 
> > 
> > 我是proxy的问题
> 
> 是关掉proxy? 我已经关掉了proxy 但是还是有这个问题。很奇怪。 还有h11 timed out。 好无语啊

我设置了本地访问时候的no _proxy，但是外界用户访问的时候仍然使用原本已有的proxy

**Comment by violet17** [comment]
> > > > 怎么解决的呢？
> > > 
> > > 
> > > 我是proxy的问题
> > 
> > 
> > 是关掉proxy? 我已经关掉了proxy 但是还是有这个问题。很奇怪。 还有h11 timed out。 好无语啊
> 
> 我设置了本地访问时候的no _proxy，但是外界用户访问的时候仍然使用原本已有的proxy

我全部用的是本地访问，没有外界用户访问，也没有远程访问，不知道为啥gradio 会这样抽风

**Comment by ZeanNi** [comment]
> > > > > 怎么解决的呢？
> > > > 
> > > > 
> > > > 我是proxy的问题
> > > 
> > > 
> > > 是关掉proxy? 我已经关掉了proxy 但是还是有这个问题。很奇怪。 还有h11 timed out。 好无语啊
> > 
> > 
> > 我设置了本地访问时候的no _proxy，但是外界用户访问的时候仍然使用原本已有的proxy
> 
> 我全部用的是本地访问，没有外界用户访问，也没有远程访问，不知道为啥gradio 会这样抽风
你试一试只设置允许no_proxy的本地地址，但是不去设置proxy内容，及我下面注释的部分
import os
os.environ["no_proxy"] = "127.0.0.1,localhost"
# os.environ["http_proxy"] = ""
# os.environ["https_proxy"] = ""

**Comment by violet17** [comment]
> 只设置允许no_proxy的本地地址

嗯 我试试  多谢

**Comment by violet17** [comment]
还是不行  还是各种timed out

**Comment by CRonaldo1997** [comment]
@violet17 同样问题，请问后来解决了吗

**Comment by violet17** [comment]
> @violet17 同样问题，请问后来解决了吗

解决了。这个应该是gradio  里面的那个什么反馈引起的问题。 需要设置analytics_enabled=False
 参考：https://www.gradio.app/docs/gradio/interface

analytics_enabled： Whether to allow basic telemetry. If None, will use GRADIO_ANALYTICS_ENABLED environment variable if defined, or default to True.

**Comment by Jandown** [comment]
> > @violet17 同样问题，请问后来解决了吗
> 
> 解决了。这个应该是gradio 里面的那个什么反馈引起的问题。 需要设置analytics_enabled=False 参考：https://www.gradio.app/docs/gradio/interface
> 
> analytics_enabled： Whether to allow basic telemetry. If None, will use GRADIO_ANALYTICS_ENABLED environment variable if defined, or default to True.

这个是禁用gradio更新提示，我试了，问题依旧。

**Comment by Jandown** [comment]
我找到问题了，看看demo里是不是加载了抱抱脸的图片或资源导致的，把抱抱脸或是需要代理上网的链接去掉就可以了
