### ISSUE TITLE
idea 无法登陆 Failed to initiate the CodeGeeX login process. Please try again.

### ISSUE THREAD

**Issue by liwqcoding** [THUDM/CodeGeeX2#247]
Failed to initiate the CodeGeeX login process. Please try again.

**Comment by jerryshang0226** [comment]
同样的问题，每次启动都需要卸载插件后重新安装才可以使用

**Comment by liwqcoding** [comment]
同样的问题，写在插件，重装插件也不行，不知道和这个日志有没有关系：
```
2024-06-11 08:47:31,251 [  39413]   WARN - #ai.codegeex.plugin.lang.agent.AgentCodegeexService - error retrieving device code
java.lang.IllegalArgumentException: Url 不能解析: get: [/prod/code/oauth/getUserInfo]。
	at net.dreamlu.mica.http.HttpRequest.<init>(HttpRequest.java:231)
	at net.dreamlu.mica.http.HttpRequest.get(HttpRequest.java:113)
	at ai.codegeex.plugin.lang.agent.AgentCodegeexService$1.a(SourceFile:465)
	at ai.codegeex.plugin.lang.agent.AgentCodegeexService$1.compute(SourceFile:438)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:394)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$9(CoreProgressManager.java:567)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:86)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-06-11 08:47:31,373 [  39535]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) UnindexedFilesIndexer[cloud-parent, 6 iterators, reason: On project open]
```

**Comment by crazygo** [comment]
看起来是和网络有关，请问你的ide网络或公司网络有哪些限制呢

**Comment by dingxiaos** [comment]
Failed to initiate the CodeGeeX login process. Please try again.我也有这个问题

**Comment by hsjer** [comment]
> 启动 CodeGeeX 登录过程失败。Please try again.我也有这个问
可以尝试关闭代理
